runtime: python39

env_variables:
  ROBOFLOW_API_KEY: "l0FTZJ0g4vV7nkoUYas9"
  GCP_BUCKET_NAME: "trash-segregation-iot"
  GOOGLE_APPLICATION_CREDENTIALS: "trash-segregation-4fa9fb856caa.json"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto
  secure: always